
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author REYMOND KENNY
 */
public class BrrowedBooksList extends javax.swing.JFrame {

    /**
     * Creates new form BrrowedBooksList
     */
    public BrrowedBooksList() {
        initComponents();
       setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
             
        String query = "SELECT * FROM  `borrow`";
        
       Statement st;
       ResultSet rs;
       Connection conn = MyConnection.getConnection();
       try {
           st = conn.createStatement();
           rs = st.executeQuery(query);
           DefaultTableModel model = new DefaultTableModel();
           model.setColumnIdentifiers(new Object[]{"Student Name","Student ID","Class","Book ID","Borrowing Date","Returning Date"});
           Object []coloumn = new Object[6];
           while(rs.next())
           {
               String studentname = rs.getString("student_name");
               String studentid = rs.getString("student_id");
               String bookid = rs.getString("book_id");
               String bdate = rs.getString("received");
               String rdate = rs.getString("returnd");
               int cls = rs.getInt("class");
              
               
     
               coloumn[0]= studentname;
               coloumn[1]= studentid;
               coloumn[2]= cls;
               coloumn[3]= bookid;
               coloumn[4]= bdate;
               coloumn[5]= rdate;
               model.addRow(coloumn);    
           }
           jTable1.setModel(model);
           
       } catch (Exception e) {
           e.printStackTrace();
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        search = new javax.swing.JButton();
        Ser = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Student ID", "Class", "Book ID", "Borrowing Date", "Returning Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Received");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        search.setText("search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        Ser.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ser))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(search)
                .addGap(18, 18, 18)
                .addComponent(Ser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try
        {
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            int i= jTable1.getSelectedRow();
            if(i>=0)
            {
                
                Connection conn = MyConnection.getConnection();  
                PreparedStatement pst = null;
                String query = "DELETE FROM borrow WHERE book_id = ?";
                String bookId =  jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
                System.out.println(bookId);
                pst = conn.prepareStatement(query);
                pst.setString(1, bookId);       
                pst.execute();
                model.removeRow(i);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Please select a row from the table");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
       
        String search = Ser.getText().toString();
        String query = "SELECT * FROM `borrow` where book_id LIKE '%"+ search +"%'";
        
        Statement st;
        ResultSet rs;
       Connection conn = MyConnection.getConnection();
       try {
           st = conn.createStatement();
           rs = st.executeQuery(query);
           DefaultTableModel model = new DefaultTableModel();
           model.setColumnIdentifiers(new Object[]{"Student Name","Student ID","Class","Book ID","Borrowing Date","Returning Date"});
           Object []coloumn = new Object[6];
           while(rs.next())
           {
               String studentname = rs.getString("student_name");
               String studentid = rs.getString("student_id");
               String bookid = rs.getString("book_id");
               String bdate = rs.getString("received");
               String rdate = rs.getString("returnd");
               int cls = rs.getInt("class");
              
               
     
               coloumn[0]= studentname;
               coloumn[1]= studentid;
               coloumn[2]= cls;
               coloumn[3]= bookid;
               coloumn[4]= bdate;
               coloumn[5]= rdate;
               model.addRow(coloumn);    
           }
           jTable1.setModel(model);
           
       } catch (Exception e) {
           e.printStackTrace();
       }        
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrrowedBooksList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrrowedBooksList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrrowedBooksList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrrowedBooksList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrrowedBooksList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
